spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://jirat8098:1259374Jj@tugreater.cqnov.mongodb.net/?retryWrites=true&w=majority&appName=tuGreater

spring.data.mongodb.database=tuGreater
# spring.http.encoding.charset=UTF-8
# spring.http.encoding.enabled=true
# spring.http.encoding.force=true

