spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://suteethornkav:GreaterDB@tugreater.yv8wdns.mongodb.net/?retryWrites=true&w=majority&appName=TUGreater
spring.data.mongodb.database=tuGreater
