spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://petch:Chaisiri_123@personal-cn333.mqb6i.mongodb.net/?retryWrites=true&w=majority&appName=personal-cn333
spring.data.mongodb.database=tuGreater

